marks=[]
f1=int(input())
marks.append(f1)
f2=int(input())
marks.append(f2)
f3=int(input())
marks.append(f3)
f4=int(input())
marks.append(f4)
f5=int(input())
marks.append(f5)
f6=int(input())
marks.append(f6)
marks.sort()
print(marks)

